# Generated by Django 3.1.3 on 2021-01-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='short_URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_url', models.URLField(max_length=250)),
                ('shortened_url', models.URLField(max_length=50)),
                ('visits', models.IntegerField()),
            ],
        ),
    ]
