# Generated by Django 3.1.3 on 2021-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_url',
            name='id',
        ),
        migrations.AlterField(
            model_name='short_url',
            name='complete_url',
            field=models.URLField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
