# Generated by Django 3.1.3 on 2021-01-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210101_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
